# Generated by Django 5.1.7 on 2025-05-20 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0006_remove_timestamp_feild"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="created_by",
        ),
    ]
