# Generated by Django 5.1.7 on 2025-06-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Media_Management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="images",
            field=models.JSONField(blank=True, default=list, help_text="Multiple image files"),
        ),
        migrations.AddField(
            model_name="media",
            name="video_links",
            field=models.JSONField(blank=True, default=list, help_text="Multiple video URLs"),
        ),
    ]
